
<RootWidget>:
	TabbedPanel:
		id: tab_panel
		do_default_tab: False
		tab_pos: 'bottom_left'
		tab_width: self.size[0]/len(self.tab_list)
		tab_height:60

		TabbedPanelItem:
			id:tab_position
			text:'Position'



            BoxLayout:
                orientation:'vertical'
                BoxLayout:

                    BoxLayout
                        orientation:'vertical'
                        ScrollView:

                            BoxLayout:
                                orientation:'vertical'
                                size_hint_y:None
                                height: self.minimum_height
                                id:results_scrollview


                        TextInput:
                            id:search_input
                            hint_text:'search..'
                            size_hint:(1,0.2)
                            font_size:search_input.height-search_input.height/3


                BoxLayout:
                    orientation:'vertical'
                    BoxLayout:
                        id:keyboard_numrow
                        Button:
                            text:'1'
                            on_press:root.keypress('1')
                        Button:
                            text:'2'
                            on_press:root.keypress('2')
                        Button:
                            text:'3'
                            on_press:root.keypress('3')
                        Button:
                            text:'4'
                            on_press:root.keypress('4')
                        Button:
                            text:'5'
                            on_press:root.keypress('5')
                        Button:
                            text:'6'
                            on_press:root.keypress('6')
                        Button:
                            text:'7'
                            on_press:root.keypress('7')
                        Button:
                            text:'8'
                            on_press:root.keypress('8')
                        Button:
                            text:'9'
                            on_press:root.keypress('9')
                        Button:
                            text:'0'
                            on_press:root.keypress('0')
                        Button:
                            text:'Backspace'
                            size_hint:(1.5,1)
                            on_press:root.keypress('backspace')



                    BoxLayout:
                        id:keyboard_topletters

                        Button:
                            text:'Q'
                            on_press:root.keypress('Q')
                        Button:
                            text:'W'
                            on_press:root.keypress('W')
                        Button:
                            text:'E'
                            on_press:root.keypress('E')
                        Button:
                            text:'R'
                            on_press:root.keypress('R')
                        Button:
                            text:'T'
                            on_press:root.keypress('T')
                        Button:
                            text:'Y'
                            on_press:root.keypress('Y')
                        Button:
                            text:'U'
                            on_press:root.keypress('U')
                        Button:
                            text:'I'
                            on_press:root.keypress('I')
                        Button:
                            text:'O'
                            on_press:root.keypress('O')
                        Button:
                            text:'P'
                            on_press:root.keypress('P')


                    BoxLayout:
                        id:keyboard_midletters

                        Button:
                            text:'A'
                            on_press:root.keypress('A')
                        Button:
                            text:'S'
                            on_press:root.keypress('S')
                        Button:
                            text:'D'
                            on_press:root.keypress('D')
                        Button:
                            text:'F'
                            on_press:root.keypress('F')
                        Button:
                            text:'G'
                            on_press:root.keypress('G')
                        Button:
                            text:'H'
                            on_press:root.keypress('H')
                        Button:
                            text:'J'
                            on_press:root.keypress('J')
                        Button:
                            text:'K'
                            on_press:root.keypress('K')
                        Button:
                            text:'L'
                            on_press:root.keypress('L')
                        #Button:
                        #	text:'Submit'
                        #	size_hint:(1.5,1)
                        #	on_press:root.searchAirports(search_input.text)



                    BoxLayout:
                        id:keyboard_botletters
                        Widget:
                        Button:
                            text:'Z'
                            on_press:root.keypress('Z')
                        Button:
                            text:'X'
                            on_press:root.keypress('X')
                        Button:
                            text:'C'
                            on_press:root.keypress('C')
                        Button:
                            text:'V'
                            on_press:root.keypress('V')
                        Button:
                            text:'B'
                            on_press:root.keypress('B')
                        Button:
                            text:'N'
                            on_press:root.keypress('N')
                        Button:
                            text:'M'
                            on_press:root.keypress('M')
                        Widget:





		TabbedPanelItem
			id:tab_weather
			text:'Weather'

			TabbedPanel:
				id:tab_panel_weather
				do_default_tab: False
				tab_pos: 'bottom_left'
				tab_width: self.size[0]/len(self.tab_list)
				tab_height:60


				TabbedPanelItem
					id:tab_weather_cloud
					text:'Cloud'

					BoxLayout:
						orientation:'vertical'

						BoxLayout:

							BoxLayout:
								orientation:'vertical'
								Widget:
								Label:
									text:'Base of Cloud Layer 1: ' +str(int(clouds_slider_1.value)) + ' feet'
									font_size:25
								Slider:
									id:clouds_slider_1
									min:0
									max:clouds_slider_1_top.value-4000
								Label:
									text:'Top of Cloud Layer 1: ' +str(int(clouds_slider_1_top.value)) + ' feet'
									font_size:25
								Slider:
									id:clouds_slider_1_top
									min:clouds_slider_1.value+4000
									max:40000
							BoxLayout:
								orientation:'vertical'
								Label:
									text:'Cloud Layer 1'
								BoxLayout:
									ToggleButton:
										text:'None'
										group:'1'
										allow_no_selection:False
										font_size:25
										on_state:root.setClouds(self,int(clouds_slider_1.value),int(clouds_slider_1_top.value))
										state:'down'
									ToggleButton:
										text:'Cirrus'
										group:'1'
										allow_no_selection:False
										font_size:25
										on_state:root.setClouds(self,int(clouds_slider_1.value),int(clouds_slider_1_top.value))
									ToggleButton:
										text:'Scattered'
										group:'1'
										allow_no_selection:False
										font_size:25
										on_state:root.setClouds(self,int(clouds_slider_1.value),int(clouds_slider_1_top.value))
									ToggleButton:
										text:'Broken'
										group:'1'
										allow_no_selection:False
										font_size:25
										on_state:root.setClouds(self,int(clouds_slider_1.value),int(clouds_slider_1_top.value))
									ToggleButton:
										text:'Overcast'
										group:'1'
										allow_no_selection:False
										font_size:25
										on_state:root.setClouds(self,int(clouds_slider_1.value),int(clouds_slider_1_top.value))

						BoxLayout:
							BoxLayout:
								orientation:'vertical'
								Widget:

								Label:
									text:'Base of Cloud Layer 2: ' +str(int(clouds_slider_2.value)) + ' feet'
									font_size:25
								Slider:
									id:clouds_slider_2
									min:0
									max:clouds_slider_2_top.value-4000
								Label:
									text:'Top of Cloud Layer 2: ' +str(int(clouds_slider_2_top.value)) + ' feet'
									font_size:25
								Slider:
									id:clouds_slider_2_top
									min:clouds_slider_2.value+4000
									max:40000
							BoxLayout:
								orientation:'vertical'
								Label:
									text:'Cloud Layer 2'
								BoxLayout:
									ToggleButton:
										text:'None'
										group:'2'
										allow_no_selection:False
										font_size:25
										on_state:root.setClouds(self,int(clouds_slider_2.value),int(clouds_slider_2_top.value))
										state:'down'
									ToggleButton:
										text:'Cirrus'
										group:'2'
										allow_no_selection:False
										font_size:25
										on_state:root.setClouds(self,int(clouds_slider_2.value),int(clouds_slider_2_top.value))
									ToggleButton:
										text:'Scattered'
										group:'2'
										allow_no_selection:False
										font_size:25
										on_state:root.setClouds(self,int(clouds_slider_2.value),int(clouds_slider_2_top.value))
									ToggleButton:
										text:'Broken'
										group:'2'
										allow_no_selection:False
										font_size:25
										on_state:root.setClouds(self,int(clouds_slider_2.value),int(clouds_slider_2_top.value))
									ToggleButton:
										text:'Overcast'
										group:'2'
										allow_no_selection:False
										font_size:25
										on_state:root.setClouds(self,int(clouds_slider_2.value),int(clouds_slider_2_top.value))


						BoxLayout:
							BoxLayout:
								orientation:'vertical'
								Widget:
								Label:
									text:'Base of Cloud Layer 3: ' +str(int(clouds_slider_3.value)) + ' feet'
									font_size:25
								Slider:
									id:clouds_slider_3
									min:0
									max:clouds_slider_3_top.value-4000
								Label:
									text:'Top of Cloud Layer 3: ' +str(int(clouds_slider_3_top.value)) + ' feet'
									font_size:25
								Slider:
									id:clouds_slider_3_top
									min:clouds_slider_3.value+4000
									max:40000
							BoxLayout:
								orientation:'vertical'
								Label:
									text:'Cloud Layer 3'
								BoxLayout:
									ToggleButton:
										id:clouds_none_3
										text:'None'
										group:'3'
										allow_no_selection:False
										state:'down'
										font_size:25
										on_state:root.setClouds(self,int(clouds_slider_3.value),int(clouds_slider_3_top.value))
									ToggleButton:
										text:'Cirrus'
										group:'3'
										allow_no_selection:False
										font_size:25
										on_state:root.setClouds(self,int(clouds_slider_3.value),int(clouds_slider_3_top.value))
									ToggleButton:
										text:'Scattered'
										group:'3'
										allow_no_selection:False
										font_size:25
										on_state:root.setClouds(self,int(clouds_slider_3.value),int(clouds_slider_3_top.value))
									ToggleButton:
										text:'Broken'
										group:'3'
										allow_no_selection:False
										font_size:25
										on_state:root.setClouds(self,int(clouds_slider_3.value),int(clouds_slider_3_top.value))
									ToggleButton:
										text:'Overcast'
										group:'3'
										allow_no_selection:False
										font_size:25
										on_state:root.setClouds(self,int(clouds_slider_3.value),int(clouds_slider_3_top.value))




				TabbedPanelItem
					id:tab_weather_wind
					text:'Wind'
					BoxLayout:
						orientation:'vertical'
						Widget:
							size_hint:(0.1,0.1)
						BoxLayout:
							orientation:'vertical'
							Label:
							    text:'Wind Layer - Low'
							    font_size:25
							BoxLayout:

								Slider:
									id:winds_slider_altitude_1
									min:0
									max:36000
									size_hint:(2,1)
                                    on_value:root.sliderSystem('sim/weather/wind_altitude_msl_m[0]',winds_slider_altitude_1.value)
								Label:
									text: 'Wind 1 Altitude: ' + str(int(winds_slider_altitude_1.value))
									font_size:25

							BoxLayout:
								Slider:
									id:winds_slider_direction_1
									min:0
									max:360
									size_hint:(2,1)
									on_value:root.sliderSystem('sim/weather/wind_direction_degt[0]',winds_slider_direction_1.value)
								Label:
									text: 'Wind 1 Direction from North: ' + str(int(winds_slider_direction_1.value))
									font_size:25

							BoxLayout:
								Slider:
									id:winds_slider_speed_1
									min:0
									max:200
									size_hint:(2,1)
									on_value:root.sliderSystem('sim/weather/wind_speed_kt[0]',winds_slider_speed_1.value)
								Label:
									text: 'Wind 1 Speed: ' + str(int(winds_slider_speed_1.value))
									font_size:25

							BoxLayout:
								Slider:
									id:winds_slider_sheardirection_1
									min:0
									max:359
									size_hint:(2,1)
									on_value:root.sliderSystem('sim/weather/shear_direction_degt[0]',winds_slider_sheardirection_1.value)
								Label:
									text: 'Wind Shear 1 Direction from North: ' + str(int(winds_slider_sheardirection_1.value))
									font_size:25
							BoxLayout:
								Slider:
									id:winds_slider_shearspeed_1
									min:0
									max:200
									size_hint:(2,1)
									on_value:root.sliderSystem('sim/weather/shear_speed_kt[0]',winds_slider_shearspeed_1.value)
								Label:
									text: 'Wind 1 Shear Speed: ' + str(int(winds_slider_shearspeed_1.value))
									font_size:25
							BoxLayout:
								Slider:
									id:winds_slider_turbulence_1
									min:0
									max:10
									size_hint:(2,1)
									on_value:root.sliderSystem('sim/weather/turbulence[0]',winds_slider_turbulence_1.value)
								Label:
									text: 'Wind 1 Turbulence: ' + str(int(winds_slider_turbulence_1.value))
									font_size:25
                            Widget:
                                size_hint:(1,1)
                            Label:
                                text:'Wind Layer - Mid'
                                font_size:25
                            BoxLayout:

								Slider:
									id:winds_slider_altitude_2
									min:winds_slider_altitude_1.value+2000
									max:38000
									size_hint:(2,1)
                                    on_value:root.sliderSystem('sim/weather/wind_altitude_msl_m[1]',winds_slider_altitude_2.value)
								Label:
									text: 'Wind 2 Altitude: ' + str(int(winds_slider_altitude_2.value))
									font_size:25

							BoxLayout:
								Slider:
									id:winds_slider_direction_2
									min:0
									max:360
									size_hint:(2,1)
									on_value:root.sliderSystem('sim/weather/wind_direction_degt[1]',winds_slider_direction_2.value)
								Label:
									text: 'Wind 2 Direction from North: ' + str(int(winds_slider_direction_2.value))
									font_size:25

							BoxLayout:
								Slider:
									id:winds_slider_speed_2
									min:0
									max:200
									size_hint:(2,1)
									on_value:root.sliderSystem('sim/weather/wind_speed_kt[1]',winds_slider_speed_2.value)
								Label:
									text: 'Wind 2 Speed: ' + str(int(winds_slider_speed_2.value))
									font_size:25

							BoxLayout:
								Slider:
									id:winds_slider_sheardirection_2
									min:0
									max:359
									size_hint:(2,1)
									on_value:root.sliderSystem('sim/weather/shear_direction_degt[1]',winds_slider_sheardirection_2.value)
								Label:
									text: 'Wind Shear 2 Direction from North: ' + str(int(winds_slider_sheardirection_2.value))
									font_size:25
							BoxLayout:
								Slider:
									id:winds_slider_shearspeed_2
									min:0
									max:200
									size_hint:(2,1)
									on_value:root.sliderSystem('sim/weather/shear_speed_kt[1]',winds_slider_shearspeed_2.value)
								Label:
									text: 'Wind 2 Shear Speed: ' + str(int(winds_slider_shearspeed_2.value))
									font_size:25
							BoxLayout:
								Slider:
									id:winds_slider_turbulence_2
									min:0
									max:10
									size_hint:(2,1)
									on_value:root.sliderSystem('sim/weather/turbulence[1]',winds_slider_turbulence_2.value)
								Label:
									text: 'Wind 2 Turbulence: ' + str(int(winds_slider_turbulence_2.value))
									font_size:25

							Widget:
                                size_hint:(1,1)
                            Label:
                                text:'Wind Layer - High'
                                font_size:25
                            BoxLayout:

								Slider:
									id:winds_slider_altitude_3
									min:winds_slider_altitude_2.value+2000
									max:40000
									size_hint:(2,1)
                                    on_value:root.sliderSystem('sim/weather/wind_altitude_msl_m[2]',winds_slider_altitude_3.value)
								Label:
									text: 'Wind 3 Altitude: ' + str(int(winds_slider_altitude_3.value))
									font_size:25

							BoxLayout:
								Slider:
									id:winds_slider_direction_3
									min:0
									max:360
									size_hint:(2,1)
									on_value:root.sliderSystem('sim/weather/wind_direction_degt[2]',winds_slider_direction_3.value)
								Label:
									text: 'Wind 3 Direction from North: ' + str(int(winds_slider_direction_3.value))
									font_size:25

							BoxLayout:
								Slider:
									id:winds_slider_speed_3
									min:0
									max:200
									size_hint:(2,1)
									on_value:root.sliderSystem('sim/weather/wind_speed_kt[2]',winds_slider_speed_3.value)
								Label:
									text: 'Wind 3 Speed: ' + str(int(winds_slider_speed_3.value))
									font_size:25

							BoxLayout:
								Slider:
									id:winds_slider_sheardirection_3
									min:0
									max:359
									size_hint:(2,1)
									on_value:root.sliderSystem('sim/weather/shear_direction_degt[2]',winds_slider_sheardirection_3.value)
								Label:
									text: 'Wind Shear 3 Direction from North: ' + str(int(winds_slider_sheardirection_3.value))
									font_size:25
							BoxLayout:
								Slider:
									id:winds_slider_shearspeed_3
									min:0
									max:200
									size_hint:(2,1)
									on_value:root.sliderSystem('sim/weather/shear_speed_kt[2]',winds_slider_shearspeed_3.value)
								Label:
									text: 'Wind 3 Shear Speed: ' + str(int(winds_slider_shearspeed_3.value))
									font_size:25
							BoxLayout:
								Slider:
									id:winds_slider_turbulence_3
									min:0
									max:10
									size_hint:(2,1)
									on_value:root.sliderSystem('sim/weather/turbulence[2]',winds_slider_turbulence_3.value)
								Label:
									text: 'Wind 3 Turbulence: ' + str(int(winds_slider_turbulence_3.value))
									font_size:25
					    Widget:
					        size_hint:(0.1,0.1)





				TabbedPanelItem:
					id:tab_weather_ambient
					text:'Ambience'
					BoxLayout:
						orientation:'vertical'
						BoxLayout:
							Slider:
								id:slider_temp
								min:-10
								max:40
								step:1
								on_value:root.sliderSystem('sim/weather/temperature_sealevel_c',slider_temp.value)
							Label:
								text: 'Temperature at sea level : ' + str(int(slider_temp.value)) + ' Degrees C'
								font_size:25

						BoxLayout:
							Slider:
								id:slider_baro
								min:27
								max:34
								step:0.1
								on_value:root.sliderSystem('sim/weather/barometer_sealevel_inhg',slider_baro.value)
							Label:
								text: 'Barometer at sea level :' + str(float(slider_baro.value)) + ' hg'
								font_size:25

						BoxLayout:
							Slider:
								id:slider_turbulence
								min:0
								max:1
								step:0.01
								on_value:root.sliderSystem('sim/weather/wind_turbulence_percent',slider_turbulence.value)
							Label:
								text: 'Turbluence % :' + str(float(slider_turbulence.value)*100)
								font_size:25

						BoxLayout:
							Slider:
								id:slider_rain
								min:0
								max:1
								step:0.01
								on_value:root.sliderSystem('sim/weather/rain_percent',slider_rain.value)
							Label:
								text: 'Rain % : ' + str(float(slider_rain.value)*100)
								font_size:25

						BoxLayout:
							Slider:
								id:slider_storm
								min:0
								max:1
								step:0.01
								on_value:root.sliderSystem('sim/weather/thunderstorm_percent',slider_storm.value)
							Label:
								text: 'Storm % : ' + str(float(slider_storm.value)*100)
								font_size:25

					    BoxLayout:
							Slider:
								id:slider_visibility
								min:91
								max:160000
								step:
								on_value:root.sliderSystem('sim/weather/visibility_reported_m',slider_visibility.value)
							Label:
								text: 'Visibility (m) : ' + str(int(slider_visibility.value))
								font_size:25



				TabbedPanelItem:
					id:tab_weather_time
					text:'Time'
					BoxLayout:
						orientation:'vertical'

                        BoxLayout:

					        Widget:
					        Label:
						        id:time_hours
						        text:'Zulu Time: 0:'
						        font_size:25
						        size_hint:(0.4,1)

						    Label:
						        id:time_minutes
						        text:'00'
						        font_size:25
						        size_hint:(0.1,1)
						    Widget:
						    Label:
						        id:local_time_hours
						        text:'Local Time: 0:'
						        font_size:25
						        size_hint:(0.4,1)
						    Label:
						        id:local_time_minutes
						        text:'00'
						        font_size:25
						        size_hint:(0.1,1)
						    Widget:



						Slider:
							id:time_hours_slider
							min:0000
							max:86400
							step:1
							on_value:root.setTime('sim/time/zulu_time_sec',(int(time_hours_slider.value)))




				TabbedPanelItem:
					id:tab_weather_preset
					text:'Preset'
					BoxLayout:
					    BoxLayout:
					        BoxLayout:
					            orientation:'vertical'
					            Widget:
					                size_hint:(0.1,0.1)

					            Button:
					                text:'CAVOK'
					                font_size:25
					                on_press:root.weatherPresets('CAVOK')
					            Widget:
					                size_hint:(0.1,0.1)
					            Button:
					                text:'VFR'
					                font_size:25
					                on_press:root.weatherPresets('VFR')
					            Widget:
					                size_hint:(0.1,0.1)
					        Widget:
					            size_hint:(0.1,0.1)

					        BoxLayout:
					            orientation:'vertical'
					            Widget:
					                size_hint:(0.1,0.1)

					            Button:
					                text:'Marginal VFR'
					                font_size:25
					                on_press:root.weatherPresets('MarginalVFR')
					            Widget:
					                size_hint:(0.1,0.1)
					            Button:
					                text:'IFR Cat 1'
					                font_size:25
					                on_press:root.weatherPresets('IFRCat1')


					            Widget:
					                size_hint:(0.1,0.1)

                            Widget:
                                size_hint:(0.1,0.1)


					        BoxLayout:
					            orientation:'vertical'
					            Widget:
					                size_hint:(0.1,0.1)
                                Button:
					                text:'Non Precision'
					                font_size:25
					                on_press:root.weatherPresets('NonPrecision')
                                Widget:
					                size_hint:(0.1,0.1)
					            Button:
					                text:'IFR Cat 2'
					                font_size:25
					                on_press:root.weatherPresets('IFRCat2')

					            Widget:
					                size_hint:(0.1,0.1)
                            Widget:
                                size_hint:(0.1,0.1)
					        BoxLayout:
					            orientation:'vertical'
					            Widget:
					                size_hint:(0.1,0.1)
					            Button:
					                text:'Stormy'
					                font_size:25
					                on_press:root.weatherPresets('Stormy')

					            Widget:
					                size_hint:(0.1,0.1)
					            Button:
					                text:'IFR Cat 3'
					                font_size:25
					                on_press:root.weatherPresets('IFRCat3')
					            Widget:
					                size_hint:(0.1,0.1)






		TabbedPanelItem:
			id:tab_weight
			text:'Weight'
			BoxLayout:
				orientation:'vertical'
				BoxLayout:
					Slider:
						id:slider_fuel
						min:0
						max:420
						value:200
						on_value:root.sliderSystem('sim/flightmodel/weight/m_fuel1',slider_fuel.value)
					Label:
						font_size:25
						text:'Fuel Weight: ' + str(int(slider_fuel.value))
				BoxLayout:
					Slider:
						id:slider_cg
						min:-0.9
						max:0.18
						step:0.01
						on_value:root.sliderSystem('sim/flightmodel/misc/cgz_ref_to_default',slider_cg.value)

					Label:
						font_size:25
						text:'Center of Gravity: ' + str(float(slider_cg.value))
				BoxLayout:
					Slider:
						id:slider_payload_weight
						min:0
						max:5400
						on_value:root.sliderSystem('sim/flightmodel/weight/m_fixed',slider_payload_weight.value)
					Label:
						font_size:25
						text:'Payload Weight:' + str(int(slider_payload_weight.value))
				BoxLayout:
					Slider:
						id:slider_zfw
						min:0
						max:2500
						value:1334
						on_value:root.sliderSystem('sim/aircraft/weight/acf_m_empty',slider_zfw.value)
					Label:
						font_size:25
						text:'ZFW: '+ str(int(slider_zfw.value))


		TabbedPanelItem:
			id:tab_failure
			text:'Failures'
			TabbedPanel:
				id:tab_panel_failure
				do_default_tab: False
				tab_pos: 'bottom_left'
				tab_width: self.size[0]/len(self.tab_list)
				tab_height:60



                TabbedPanelItem:
                    id:tab_aircraft_failures_electrical
                    text:'Electrical'
                    BoxLayout:
                        BoxLayout:
                            BoxLayout:
                                orientation:'vertical'
                                BoxLayout:
                                    Label:
                                        text:'Battery Over Temp'

                                    Switch:
                                        id:fail_battery_over_temp_switch
                                        text:'debug/missing'
                                        on_active:root.failSystem2(self)

                                Spinner:
                                    id:fail_battery_over_temp_spinner
                                    values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
                                    text:'Not Set'
                                    on_text:root.setFails(self,fail_battery_over_temp_switch)

                                Widget:
                                    size_hint:(0.1,0.1)


                                BoxLayout:
                                    Label:

                                        text:'Battery Offline'
                                    Switch:
                                        id:fail_battery_offline_switch
                                        text:'sim/operation/failures/rel_batter0'
                                        on_active:root.failSystem2(self)

                                Spinner:
                                    id:fail_battery_offline_spinner
                                    values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
                                    text:'Not Set'
                                    on_text:root.setFails(self,fail_battery_offline_switch)

                                Widget:
                                    size_hint:(0.1,0.1)

                            BoxLayout:
                                orientation:'vertical'
                                BoxLayout:
                                    Label:
                                        text:'DC Gen Offline - Cannot Set This'

                                    Switch:
                                        id:fail_gen_offline_switch
                                        text:'sim/operation/failures/rel_genera0'
                                        on_active:root.failSystem2(self)

                                Spinner:
                                    id:fail_gen_offline_spinner
                                    values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'

                                    text:'Not Set'
                                    on_text:root.setFails(self,fail_gen_offline_switch)
                                Widget:
                                    size_hint:(0.1,0.1)


                                BoxLayout:
                                    Label:
                                        text:'Landing Light Failure'

                                    Switch:
                                        id:fail_landing_light_switch
                                        text:'sim/operation/failures/rel_lites_land'
                                        on_active:root.failSystem2(self)

                                Spinner:
                                    id:fail_landing_light_spinner

                                    values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
                                    text:'Not Set'
                                    on_text:root.setFails(self,fail_landing_light_switch)
                                Widget:
                                    size_hint:(0.1,0.1)


                            BoxLayout:
                                orientation:'vertical'
                                BoxLayout:
                                    Label:

                                        text:'Instrument Light Failure'
                                    Switch:
                                        id:fail_instrument_light_switch
                                        font_size:25
                                        text:'sim/operation/failures/rel_lites_ins'
                                        on_active:root.failSystem2(self)

                                Spinner:
                                    id:fail_instrument_light_spinner
                                    values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
                                    text:'Not Set'
                                    on_text:root.setFails(self,fail_instrument_light_switch)

                                Widget:
                                    size_hint:(0.1,0.1)


                                BoxLayout:
                                    Label:

                                        text:'Electrical Bus Failure'
                                    Switch:

                                        id:fail_electrical_bus_switch
                                        text:'sim/operation/failures/rel_esys'
                                        on_active:root.failSystem2(self)

                                Spinner:
                                    id:fail_electrical_bus_spinner
                                    values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
                                    text:'Not Set'

                                    on_text:root.setFails(self,fail_electrical_bus_switch)
                                Widget:
                                    size_hint:(0.1,0.1)




                TabbedPanelItem:
                    id:tab_aircraft_failures_controls
                    text:'Controls'
                    BoxLayout:
                        BoxLayout:
                            BoxLayout:
                                orientation:'vertical'

                                BoxLayout:
                                    Label:
                                        text:'Rudder Trim Runaway'
                                    Switch:
                                        id:fail_rudder_trim_runaway_switch
                                        text:'sim/operation/failures/rel_rud_trim_run'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_rudder_trim_runaway_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_rudder_trim_runaway_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                                BoxLayout:
                                    Label:
                                        text:'Rudder Trim'
                                    Switch:
                                        id:fail_rudder_trim_switch
                                        text:'sim/operation/failures/rel_trim_rud'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_rudder_trim_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_rudder_trim_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                            BoxLayout:
                                orientation:'vertical'

                                BoxLayout:
                                    Label:
                                        text:'Complete Loss Tail Rotor Effect'
                                    Switch:
                                        id:fail_tail_rotor_effect_loss_switch
                                        text:'sim/operation/failures/rel_trotor'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_tail_rotor_effect_loss_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_tail_rotor_effect_loss_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                                BoxLayout:
                                    Label:
                                        text:'Major GOV Failure'
                                    Switch:
                                        id:fail_major_gov_switch
                                        text:'sim/operation/failures/rel_govnr_0'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_major_gov_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_major_gov_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                            BoxLayout:
                                orientation:'vertical'

                                BoxLayout:
                                    Label:
                                        text:'GOV fail to fine'
                                    Switch:
                                        id:fail_gov_fine_switch
                                        text:'sim/operation/failures/rel_prpfin0'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_gov_fine_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_gov_fine_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                                BoxLayout:
                                    Label:
                                        text:'GOV fail to coarse'
                                    Switch:
                                        id:fail_gov_coarse_switch
                                        text:'sim/operation/failures/rel_prpcrs0'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_gov_coarse_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_gov_coarse_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                            BoxLayout:
                                orientation:'vertical'

                                BoxLayout:
                                    Label:
                                        text:'Driveshaft Fail'
                                    Switch:
                                        id:fail_driveshaft_switch
                                        text:'sim/operation/failures/rel_pshaft0'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_driveshaft_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_driveshaft_switch)
							    Widget:
							        size_hint:(2.2,2.2)









				TabbedPanelItem:
					id:tab_failure_instruments
					text:'Instruments'

					BoxLayout:
					    BoxLayout:

					        BoxLayout:
					            orientation:'vertical'
					            BoxLayout:
                                    Label:
                                        text:'Pitot Heating Inop'
                                    Switch:
                                        id:fail_pitot_heating_inop_switch
                                        text:'sim/operation/failures/rel_ice_pitot_heat1'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_pitot_heating_inop_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_pitot_heating_inop_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                                BoxLayout:
                                    Label:
                                        text:'VSI'
                                    Switch:
                                        id:fail_vsi_switch
                                        text:'sim/operation/failures/rel_ss_vvi'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_vsi_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_vsi_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                                BoxLayout:
                                    Label:
                                        text:'Static Heating Inop'
                                    Switch:
                                        id:fail_static_heating_switch
                                        text:'sim/operation/failures/rel_ice_static_heat'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_static_heating_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_static_heating_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                            BoxLayout:
                                orientation:'vertical'

                                BoxLayout:
                                    Label:
                                        text:'Pitot Blockage'
                                    Switch:
                                        id:fail_pitot_blockage_switch
                                        text:'sim/operation/failures/rel_pitot'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_pitot_blockage_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_pitot_blockage_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                                BoxLayout:
                                    Label:
                                        text:'Static Blocked'
                                    Switch:
                                        id:fail_static_blocked_switch
                                        text:'sim/operation/failures/rel_static'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_static_blocked_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_static_blocked_switch)
                                Widget:
                                    size_hint:(0.1,0.1)


                                BoxLayout:
                                    Label:
                                        text:'Airspeed Indicator'
                                    Switch:
                                        id:fail_airspeed_indicator_switch
                                        text:'sim/operation/failures/rel_ss_asi'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_airspeed_indicator_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_airspeed_indicator_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                            BoxLayout:
                                orientation:'vertical'

                                BoxLayout:
                                    Label:
                                        text:'Artificial Horizon'
                                    Switch:
                                        id:fail_artificial_horizon_switch
                                        text:'sim/operation/failures/rel_ss_ahz'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_artificial_horizon_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_artificial_horizon_switch)
                                Widget:
                                    size_hint:(0.1,0.1)


                                BoxLayout:
                                    Label:
                                        text:'Altimeter'
                                    Switch:
                                        id:fail_altimeter_switch
                                        text:'sim/operation/failures/rel_ss_alt'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_altimeter_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_altimeter_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                                Widget:
                                    size_hint:(2.1,2.1)

                            BoxLayout:
                                orientation:'vertical'

                                BoxLayout:
                                    Label:
                                        text:'Turn Indicator'
                                    Switch:
                                        id:fail_turn_indicator_switch
                                        text:'sim/operation/failures/rel_ss_tsi'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_turn_indicator_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_turn_indicator_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                                BoxLayout:
                                    Label:
                                        text:'Directional Gyro'
                                    Switch:
                                        id:fail_directional_gyro_switch
                                        text:'sim/operation/failures/rel_ss_dgy'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_directional_gyro_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_directional_gyro_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                                BoxLayout:
                                    Label:
                                        text:'Nav / Com 1'
                                    Switch:
                                        id:fail_nav_1_switch
                                        text:'sim/operation/failures/rel_navcom1'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_nav_1_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_nav_1_switch)
                                Widget:
                                    size_hint:(0.1,0.1)
                            BoxLayout:
                                orientation:'vertical'

                                BoxLayout:
                                    Label:
                                        text:'Nav / Com 2'
                                    Switch:
                                        id:fail_nav_2_switch
                                        text:'sim/operation/failures/rel_navcom2'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_nav_2_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_nav_2_switch)
                                Widget:
                                    size_hint:(0.1,0.1)


                                BoxLayout:
                                    Label:
                                        text:'DME'
                                    Switch:
                                        id:fail_dme_switch
                                        text:'sim/operation/failures/rel_dme'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_dme_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_dme_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                                BoxLayout:
                                    Label:
                                        text:'Localizer'
                                    Switch:
                                        id:fail_localizer_switch
                                        text:'sim/operation/failures/rel_loc'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_localizer_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_localizer_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                            BoxLayout:
                                orientation:'vertical'


                                BoxLayout:
                                    Label:
                                        text:'Glide Slope'
                                    Switch:
                                        id:fail_glide_slope_switch
                                        text:'sim/operation/failures/rel_gls'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_glide_slope_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_glide_slope_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                                BoxLayout:
                                    Label:
                                        text:'GPS - G430'
                                    Switch:
                                        id:fail_g430_switch
                                        text:'sim/operation/failures/rel_g430_gps1'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_g430_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_g430_switch)
                                Widget:
                                    size_hint:(0.1,0.1)


                                BoxLayout:
                                    Label:
                                        text:'Transponder'
                                    Switch:
                                        id:fail_transponder_switch
                                        text:'sim/operation/failures/rel_xpndr'
                                        on_active:root.failSystem2(self)
                                Spinner:
					                id:fail_transponder_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_transponder_switch)
                                Widget:
                                    size_hint:(0.1,0.1)






				TabbedPanelItem:
					id:tab_failure_engines
					text:'VEMD'

					BoxLayout:
					    BoxLayout:

					        BoxLayout:
					            orientation:'vertical'

					            BoxLayout:
					                Label:
					                    text:'VEMD Failure'
					                Switch:
					                    id:fail_vemd_switch
					                    text:'Dataref Missing'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_vemd_spinner
					                values:'-'
									text:'-'
									on_text:root.setFails(self,fail_vemd_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                                BoxLayout:
					                Label:
					                    text:'VEH param OOR'
					                Switch:
					                    id:fail_veh_param_oor_switch
					                    text:'Dataref Missing'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_veh_param_oor_spinner
					                values:'-'
									text:'-'
									on_text:root.setFails(self,fail_veh_param_oor_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                            BoxLayout:
                                orientation:'vertical'

                                BoxLayout:
					                Label:
					                    text:'TRQ Indication'
					                Switch:
					                    id:fail_trq_indication_switch
					                    text:'sim/operation/failures/rel_TRQind0'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_trq_indication_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_trq_indication_switch)
                                Widget:
                                    size_hint:(0.1,0.1)


                                BoxLayout:
					                Label:
					                    text:'Ng Indication'
					                Switch:
					                    id:fail_ng_indication_switch
					                    text:'sim/operation/failures/rel_N1_ind0'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_ng_indication_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_ng_indication_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                            BoxLayout:
                                orientation:'vertical'

                                BoxLayout:
					                Label:
					                    text:'Crosstalk'
					                Switch:
					                    id:fail_crosstalk_switch
					                    text:'Dataref Missing'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_crosstalk_spinner
					                values:'-'
									text:'-'
									on_text:root.setFails(self,fail_crosstalk_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                                BoxLayout:
					                Label:
					                    text:'FLI'
					                Switch:
					                    id:fail_fli_switch
					                    text:'Dataref Missing'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_fli_spinner
					                values:'-'
									text:'-'
									on_text:root.setFails(self,fail_fli_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                            BoxLayout:
                                orientation:'vertical'

                                BoxLayout:
					                Label:
					                    text:'Gen param Overlimit'
					                Switch:
					                    id:fail_gen_param_overlimit_switch
					                    text:'Dataref Missing'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_gen_param_overlimit_spinner
					                values:'-'
									text:'-'
									on_text:root.setFails(self,fail_gen_param_overlimit_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                                BoxLayout:
					                Label:
					                    text:'Bat param Overlimit'
					                Switch:
					                    id:fail_bat_param_overlimit_switch
					                    text:'Dataref Missing'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_bat_param_overlimit_spinner
					                values:'-'
									text:'-'
									on_text:root.setFails(self,fail_bat_param_overlimit_switch)
                                Widget:
                                    size_hint:(0.1,0.1)











				TabbedPanelItem:
					id:tab_failure_engines
					text:'Engine'

					BoxLayout:
					    BoxLayout:

					        BoxLayout:
					            orientation:'vertical'

					            BoxLayout:
					                Label:
					                    text:'Engine Flameout'
					                Switch:
					                    id:fail_engine_flameout_switch
					                    text:'sim/operation/failures/rel_engfla0'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_engine_flameout_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_engine_flameout_switch)
                                Widget:
                                    size_hint:(0.1,0.1)


					            BoxLayout:
					                Label:
					                    text:'Engine Lost Power'
					                Switch:
					                    id:fail_engine_lost_power_switch
					                    text:'sim/operation/failures/rel_engfai0'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_engine_lost_power_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_engine_lost_power_switch)
                                Widget:
                                    size_hint:(0.1,0.1)


					            BoxLayout:
					                Label:
					                    text:'Oil Over Temp'
					                Switch:
					                    id:fail_oil_over_temp_switch
					                    text:'missing_drefs'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_oil_over_temp_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_oil_over_temp_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                                BoxLayout:
					                Label:
					                    text:'Runway ITT'
					                Switch:
					                    id:fail_runway_itt_switch
					                    text:'sim/operation/failures/rel_runITT0'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_runway_itt_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_runway_itt_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                            BoxLayout:
                                orientation:'vertical'

					            BoxLayout:
					                Label:
					                    text:'Oil Low Pres'
					                Switch:
					                    id:fail_oil_low_pres_switch
					                    text:'sim/operation/failures/rel_oilpmp0'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_oil_low_pres_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_oil_low_pres_switch)

                                Widget:
                                    size_hint:(0.1,0.1)


					            BoxLayout:
					                Label:
					                    text:'Engine Fire'
					                Switch:
					                    id:fail_eng_fire_switch
					                    text:'sim/operation/failures/rel_engfir0'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_eng_fire_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_eng_fire_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

					            BoxLayout:
					                Label:
					                    text:'GOV - Minor FADEC failure'
					                Switch:
					                    id:fail_eng_fadec_switch
					                    text:'sim/operation/failures/rel_fadec_0'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_eng_fadec_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_eng_fadec_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                                BoxLayout:
					                Label:
					                    text:'Hot Start'
					                Switch:
					                    id:fail_hot_start_switch
					                    text:'sim/operation/failures/rel_hotsta0'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_hot_start_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_hot_start_switch)
                                Widget:
                                    size_hint:(0.1,0.1)



                            BoxLayout:
                                orientation:'vertical'

					            BoxLayout:
					                Label:
					                    text:'TWT Grip'
					                Switch:
					                    id:fail_twt_grip_switch
					                    text:'debug/missing'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_twt_grip_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_twt_grip_switch)
                                Widget:
                                    size_hint:(0.1,0.1)


					            BoxLayout:
					                Label:
					                    text:'ENG chip'
					                Switch:
					                    id:fail_eng_chip_switch
					                    text:'sim/operation/failures/rel_chipde0'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_eng_chip_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_eng_chip_switch)
                                Widget:
                                    size_hint:(0.1,0.1)


					            BoxLayout:
					                Label:
					                    text:'Main Gearbox - Low Oil Pres'
					                Switch:
					                    id:fail_main_gbox_low_oil_pres_switch
					                    text:'debug/missing'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_main_gbox_low_oil_pres_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_main_gbox_low_oil_pres_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                                BoxLayout:
					                Label:
					                    text:'Hung Start'
					                Switch:
					                    id:fail_hung_start_switch
					                    text:'sim/operation/failures/rel_hunsta0'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_hung_start_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_hung_start_switch)
                                Widget:
                                    size_hint:(0.1,0.1)


                            BoxLayout:
                                orientation:'vertical'

					            BoxLayout:
					                Label:
					                    text:'Main Gearbox - Oil Overheat'
					                Switch:
					                    id:fail_main_gbox_oil_overheat_switch
					                    text:'debug/missing'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_main_gbox_oil_overheat_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_main_gbox_oil_overheat_switch)
                                Widget:
                                    size_hint:(0.1,0.1)




					            BoxLayout:
					                Label:
					                    text:'Bleed Valve Failure'
					                Switch:
					                    id:fail_bleed_valve_switch
					                    text:'sim/operation/failures/rel_bleed_air_lft'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_bleed_valve_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_bleed_valve_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

					            BoxLayout:
					                Label:
					                    text:'Fuel Flow Fluctuation'
					                Switch:
					                    id:fail_fuel_flow_fluctuation_switch
					                    text:'sim/operation/failures/rel_fuelfl0'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_fuel_flow_fluctuation_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_fuel_flow_fluctuation_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                                BoxLayout:
					                Label:
					                    text:'Ignitor'
					                Switch:
					                    id:fail_ignitor_switch
					                    text:'sim/operation/failures/rel_ignitr0'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_ignitor_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_ignitor_switch)
                                Widget:
                                    size_hint:(0.1,0.1)



                            BoxLayout:
                                orientation:'vertical'

					            BoxLayout:
					                Label:
					                    text:'Compressor Stall'
					                Switch:
					                    id:fail_compressor_stall_switch
					                    text:'sim/operation/failures/rel_comsta0'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_compressor_stall_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_compressor_stall_switch)
                                Widget:
                                    size_hint:(0.1,0.1)


					            BoxLayout:
					                Label:
					                    text:'Engine Seize'
					                Switch:
					                    id:fail_engine_seize_switch
					                    text:'sim/operation/failures/rel_seize_0'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_engine_seize_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_engine_seize_switch)
                                Widget:
                                    size_hint:(0.1,0.1)


					            BoxLayout:
					                Label:
					                    text:'Engine Fuel Pump'
					                Switch:
					                    id:fail_engine_fuel_pump_switch
					                    text:'sim/operation/failures/rel_fuepmp0'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_engine_fuel_pump_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_engine_fuel_pump_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                                BoxLayout:
					                Label:
					                    text:'Starter'
					                Switch:
					                    id:fail_engine_starter_switch
					                    text:'sim/operation/failures/rel_startr0'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_engine_starter_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_engine_starter_switch)
                                Widget:
                                    size_hint:(0.1,0.1)





                TabbedPanelItem:
                    id:tab_aircraft_failures_misc
                    text:'Misc'
                    BoxLayout:
                        BoxLayout:

                            BoxLayout:
                                orientation:'vertical'
                                Widget:
                                    size_hint:(1.1,1.1)
                                BoxLayout:

                                    Slider:
                                        id:fail_pitot_ice_slider
                                        min:0
                                        max:10
                                        step:0.1
                                        text:'sim/ﬂightmodel/failures/pitot_ice'
                                        on_value:root.sliderSystem(self.text,int(self.value))
                                    Label:
                                        text:'Pitot Ice Ratio : ' + str(float(fail_pitot_ice_slider.value)) + '    NEEDS TESTING'

                                Widget:
                                    size_hint:(1.1,1.1)

                                BoxLayout:

                                    Slider:
                                        id:fail_prop_ice_slider
                                        min:0
                                        max:10
                                        step:0.1
                                        text:'sim/ﬂightmodel/failures/prop_ice'
                                        on_value:root.sliderSystem(self.text,int(self.value))
                                    Label:
                                        text:'Prop Ice Ratio : ' + str(float(fail_prop_ice_slider.value))
                                Widget:
                                    size_hint:(1.1,1.1)

                                BoxLayout:

                                    Slider:
                                        id:fail_inlet_ice_slider
                                        min:0
                                        max:10
                                        step:0.1
                                        text:'sim/ﬂightmodel/failures/inlet_ice'
                                        on_value:root.sliderSystem(self.text,int(self.value))
                                    Label:
                                        text:'Inlet Ice Ratio : ' + str(float(fail_inlet_ice_slider.value))
                                Widget:
                                    size_hint:(0.1,0.1)

                                BoxLayout:
					                Label:
					                    text:'Fuel Low Pres'
					                Switch:
					                    id:fail_fuel_lo_pres_switch
					                    text:'sim/operation/failures/rel_eng_lo0'
					                    on_active:root.failSystem2(self)


					            Spinner:
					                id:fail_fuel_lo_pres_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_fuel_lo_pres_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                            BoxLayout:
                                orientation:'vertical'

                                BoxLayout:
					                Label:
					                    text:'Fuel Filter Clogged'
					                Switch:
					                    id:fail_fuel_filter_clog_switch
					                    text:'sim/operation/failures/rel_fuel_block0'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_fuel_filter_clog_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_fuel_filter_clog_switch)
                                Widget:
                                    size_hint:(0.1,0.1)


                                BoxLayout:
					                Label:
					                    text:'Hydraulic Pressure Loss'
					                Switch:
					                    id:fail_hyd_pres_loss_switch
					                    text:'sim/operation/failures/rel_hydpmp'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_hyd_pres_loss_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_hyd_pres_loss_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                                BoxLayout:
					                Label:
					                    text:'Yaw Damper'
					                Switch:
					                    id:fail_yaw_damper_switch
					                    text:'sim/cockpit/warnings/annunciators/yaw_damper'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_yaw_damper_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_yaw_damper_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

                                BoxLayout:
					                Label:
					                    text:'Hydraulics Overpressure'
					                Switch:
					                    id:fail_hyd_overpressure_switch
					                    text:'sim/operation/failures/rel_hydoverp'
					                    on_active:root.failSystem2(self)

					            Spinner:
					                id:fail_hyd_overpressure_spinner
					                values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_hyd_overpressure_switch)
                                Widget:
                                    size_hint:(0.1,0.1)












				TabbedPanelItem
					id:tab_failure_world
					text:'World'
					BoxLayout:
						BoxLayout:

							BoxLayout:
								orientation:'vertical'
								BoxLayout:
									Label:
										text:'Smoke in Cockpit'
									Switch:
										id:fail_smoke_cockpit_switch
										text:'sim/operation/failures/rel_smoke_cpit'
										on_active:root.failSystem2(self)

								Spinner:
									id:fail_smoke_cockpit_spinner
									values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_smoke_cockpit_switch)


                                Widget:
                                    size_hint:(0.1,0.1)


								BoxLayout:
									Label:
										text:'Door Open - Clarify'
									Switch:
										id:fail_door_open_switch
										text:'sim/operation/failures/rel_door_open'
										on_active:root.failSystem2(self)

								Spinner:
									id:fail_door_open_spinner
									values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_door_open_switch)

                                Widget:
                                    size_hint:(0.1,0.1)

								BoxLayout:
									Label:
										text:'External Power'
									Switch:
										id:fail_external_power_switch
										text:'sim/operation/failures/rel_ex_power_on'
										on_active:root.failSystem2(self)

								Spinner:
									id:fail_external_power_spinner
									values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_external_power_switch)

                                Widget:
                                    size_hint:(0.1,0.1)

                            BoxLayout:
                                orientation:'vertical'

								BoxLayout:
									Label:
										text:'Passenger 02'
									Switch:
										id:fail_passenger02_switch
										text:'sim/operation/failures/rel_pass_o2_on'
										on_active:root.failSystem2(self)

								Spinner:
									id:fail_passenger02_spinner
									values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_passenger02_switch)

                                Widget:
                                    size_hint:(0.1,0.1)





								BoxLayout:
									Label:
										text:'Wind Shear/MicroBurst'
									Switch:
										id:fail_microburst_switch
										text:'sim/operation/failures/rel_wind_shear'
										on_active:root.failSystem2(self)

								Spinner:
									id:fail_microburst_spinner
									values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_microburst_switch)



                                Widget:
                                    size_hint:(0.1,0.1)

								BoxLayout:
									Label:
										text:'Pilot Vertigo'
									Switch:
										id:fail_vertigo_switch
										text:'sim/operation/failures/rel_make_vertigo'
										on_active:root.failSystem2(self)

								Spinner:
									id:fail_vertigo_spinner
									values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_vertigo_switch)


                                Widget:
                                    size_hint:(0.1,0.1)

                            BoxLayout:
                                orientation:'vertical'

								BoxLayout:
									Label:
										text:'Water in Fuel'
									Switch:
										id:fail_water_fuel_switch
										text:'sim/operation/failures/rel_fuel_water'
										on_active:root.failSystem2(self)

								Spinner:
									id:fail_water_fuel_spinner
									values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_water_fuel_switch)

                                Widget:
                                    size_hint:(0.1,0.1)


								BoxLayout:
									Label:
										text:'Wrong Fuel Type'
									Switch:
										id:fail_wrong_fuel_switch
										text:'sim/operation/failures/rel_fuel_type'
										on_active:root.failSystem2(self)

								Spinner:
									id:fail_wrong_fuel_spinner
									values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_wrong_fuel_switch)
                                Widget:
                                    size_hint:(0.1,0.1)

								BoxLayout:
									Label:
										text:'Fuel Tank Filter Block'
									Switch:
										id:fail_fuel_filter_switch
										text:'sim/operation/failures/rel_fuel_block0'
										on_active:root.failSystem2(self)

								Spinner:
									id:fail_fuel_filter_spinner
									values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_fuel_filter_switch)


                                Widget:
                                    size_hint:(0.1,0.1)

                            BoxLayout:
                                orientation:'vertical'

								BoxLayout:
									Label:
										text:'VASI Inoperative'
									Switch:
										id:fail_vasi_switch
										text:'sim/operation/failures/rel_vasi'
										on_active:root.failSystem2(self)

								Spinner:
									id:fail_vasi_spinner
									values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_vasi_switch)


                                Widget:
                                    size_hint:(0.1,0.1)


								BoxLayout:
									Label:
										text:'Runway Lights Out'
									Switch:
										id:fail_runway_lights_switch
										text:'sim/operation/failures/rel_rwy_lites'
										on_active:root.failSystem2(self)

								Spinner:
									id:fail_runway_lights_spinner
									values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_runway_lights_switch)


                                Widget:
                                    size_hint:(0.1,0.1)

								BoxLayout:
									Label:
										text:'Bird Strike'
									Switch:
										id:fail_bird_strike_switch
										text:'sim/operation/failures/rel_bird_strike'
										on_active:root.failSystem2(self)

								Spinner:
									id:fail_bird_strike_spinner
									values:'Not Set','Fail at Speed','Fail at Altitude','Fail at Time'
									text:'Not Set'
									on_text:root.setFails(self,fail_bird_strike_switch)

                                Widget:
                                    size_hint:(0.1,0.1)

				TabbedPanelItem
					id:tab_failure_repairall
					text:'Repair All'
					on_press:root.fixAllSystems()
					BoxLayout:
						Label:
							text:'All Systems Repaired'


		TabbedPanelItem
			id:tab_sim_rate
			text:'Sim Rate'
			BoxLayout:
				orientation:'vertical'
				Widget:

				Label:
					text:'Sim Rate'
					font_size:25
					size:(50,50)
				Label:
					id:slider_val_label
					text:str(sim_rate_slider.value)+'x'
					size:(50,50)
					font_size:25

				Slider:
					id:sim_rate_slider
					text:'Sim Rate'
					min:1
					max:4
					step:1
				Button:
					id:sim_rate_update
					text:'Apply Speed Change'
					font_size:25
					on_press:root.applySpeed(sim_rate_slider.value)



				Widget:



		TabbedPanelItem
			id:tab_freeze
			text:'Freeze'
			AnchorLayout:
				ToggleButton:
					text:'Pause'
					size_hint: (.5,.5)
					on_press:root.pause()

